version: '2'
services:
  hashagime:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1323:1323"
    volumes:
      - .:/go/src/hashagime
      - /go/src/hashagime/vendor
    cpu_quota: 85000
    mem_limit: 3g
